version: "3.9"

services:
  iglv-rn:
    build:
      context: .
    environment:
      - NODE_ENV=development
    tty: true
    ports:
      - "19007:19007"
      - "19001:19001"
      - "5556:5556"
    expose:
      - "19000"
      - "19006"
    volumes:
      - .:/home/node/iglv-rn
    healthcheck:
      disable: true
